// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsisdnBlockList.Data;

namespace MsisdnBlockList.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220409225322_AppUsers")]
    partial class AppUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MsisdnBlockList.Data.AppUsers", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("firstname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("lastname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("mobile")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nameIdentifier")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("provider")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("roles")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("userId");

                    b.ToTable("appUsers");
                });

            modelBuilder.Entity("MsisdnBlockList.Models.Log", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("msisdn_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.HasIndex("user_id");

                    b.ToTable("log");
                });

            modelBuilder.Entity("MsisdnBlockList.Models.MSISDN", b =>
                {
                    b.Property<int>("msisdn_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("msisdn")
                        .IsRequired()
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnName("user_id")
                        .HasColumnType("int");

                    b.HasKey("msisdn_id");

                    b.HasIndex("user_id");

                    b.ToTable("msisdn");
                });

            modelBuilder.Entity("MsisdnBlockList.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("user_id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("MsisdnBlockList.Models.Log", b =>
                {
                    b.HasOne("MsisdnBlockList.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MsisdnBlockList.Models.MSISDN", b =>
                {
                    b.HasOne("MsisdnBlockList.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
